name: test workflow to exec other branch
on:
    push:
jobs:
    other-branch-job:
        runs-on: ubuntu-latest
        steps:
            - name: test job
            run: echo "execute other branch workflow!"